site_name: GFICLEE

nav:
### add your custom pages hierarchy here
  - About: index.md
  - Quick start: start.md
  - Examples: usage.md
  - Filter HGT: HGT.md

theme:
  name: mkdocs
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

# add theme version number here
extra:
  version: 0.4.0
